# Generated by Django 3.2 on 2022-06-10 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('edicao', models.CharField(max_length=50, verbose_name='Edição')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('materia', models.CharField(max_length=50, verbose_name='Matéria')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name=' Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de atualização')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimos_livros.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criaçãp')),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de atualização')),
                ('data_entrega', models.DateTimeField(verbose_name='Data de entrega')),
                ('situacao', models.CharField(choices=[('Devolvido', 'Devolvido'), ('Em empréstimo', 'Em empréstimo')], max_length=50, verbose_name='Situação')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emprestimos_livros.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='GRR')),
            ],
            options={
                'verbose_name_plural': 'Empréstimos',
            },
        ),
    ]
